### ISSUE TITLE
haikuports.conf: TARGET_ARCHITECTURE is mandatory

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuporter#135]
For some time I had issues when building with haikuporter under 64bit Haiku. I got these errors:

```
Fetching package for haiku_devel ...
Nothing to do.
'NoneType' object has no attribute 'packageInfo'
```
and
```
build-requires "haiku_devel" of package "streamradio-0.0.3_14" could not be resolved
Error: unable to resolve required packages for build for streamradio-0.0.3_14
Error:  dependency-infos:
Error:          /Source/haikuports/_x86_64/repository/streamradio-0.0.3_14.DependencyInfo
Error:          /Source/haikuports/_x86_64/repository/streamradio_source-0.0.3_14.DependencyInfo
Error:  repositories:
Error:          [u'/Source/haikuports/_x86_64/packages', '/boot/system/packages']
```

In haikuports.conf it says:
```
# TARGET_ARCHITECTURE:
#     The primary architectures you wish to compile recipes for.
#     Defaults to the current primary platform.
```

Apparently, it does not default to the primary platform on 64bit...
I'm pretty sure I used my haikuports.conf that doesn't declare TARGET_ARCHITECTURE successfully before. It does work now, after I added `TARGET_ARCHITECTURE="x86_64"`.

So, either haikuporters behaviour wrt a default target should be fixed, or the above comment changed.

**Comment by diversys** [comment]
It looks like this regression was introduced in 98b39f626de6db677e7dd006faf95ac8c1aba72c.

**Comment by mmlr** [comment]
Thanks @humdingerb for connecting the dots. With this info I was able to reproduce the issue.
